package com.android.bazemom.popularmovies.moviemodel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
//import javax.annotation.Generated;

// This holds one page full of (not-detailed) Movies.  This was generated by http://www.jsonschema2pojo.org/
// with the parameters source: JSON, Annotation style: GSON, use Primitive types, use double numbers
// (in hindsight float would have been fine), include getters/setters, and allow additional properties
//
// I modified the generated class to use MovieModel class for the results list - which causes
// Retrofit to translate the whole enchilada into my moviemodel Java objects.  Sweet!
//
//@Generated("org.jsonschema2pojo")
public class MovieResults {
    public final static String TAG = "MovieResults";

    private int page;
    private List<MovieModel> results = new ArrayList<MovieModel>();
    private int totalPages;
    private int totalResults;
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    /**
     *
     * @return
     * The page
     */
    public int getPage() {
        return page;
    }

    /**
     *
     * @param page
     * The page
     */
    public void setPage(int page) {
        this.page = page;
    }

    /**
     *
     * @return
     * The results
     */
    public List<MovieModel> getResults() {
        return results;
    }

    /**
     *
     * @param results
     * The results
     */
    public void setResults(List<MovieModel> results) {
        this.results = results;
    }

    /**
     *
     * @return
     * The totalPages
     */
    public int getTotalPages() {
        return totalPages;
    }

    /**
     *
     * @param totalPages
     * The total_pages
     */
    public void setTotalPages(int totalPages) {
        this.totalPages = totalPages;
    }

    /**
     *
     * @return
     * The totalResults
     */
    public int getTotalResults() {
        return totalResults;
    }

    /**
     *
     * @param totalResults
     * The total_results
     */
    public void setTotalResults(int totalResults) {
        this.totalResults = totalResults;
    }

    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
